[global]
# Theme to use for light mode - default themes: autumn, default
theme = "strawmelonjuice-light"
# Theme to use for dark mode - default themes: night, default-dark
theme_dark = "strawmelonjuice-dark"
# For some browsers, this will change the colour of UI elements such as the address bar
# and the status bar on mobile devices.
# This is a hex colour, e.g. #FFFFFF
colour = "#FFFFFF"
# Your website's name, displayed in various places
site_name = "Mar's site"
# A brief description of your website
site_description = "M"

[server]
# Port number for the web server
port = 8080
# Host address for the web server
host = "localhost"

[integrations]
# Enable git integration for the website
# This will allow Cynthia Mini to detect the git repository
# For example linking to the commit hash in the footer
git = true

[posts]
# Enable comments on posts using utteranc.es
# Format: "username/repositoryname"
#
# You will need to give the utterances bot access to your repo.
# See https://github.com/apps/utterances to add the utterances bot to your repo
comment_repo = "strawmelonjuice/strawmelonjuice.dev"

[variables]
strawmelonjuice_badges = """

[
  {
    "src": "/assets/img/badges/feminism.gif",
    "alt": "feminism",
    "title": "intersectional feminism!",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "/assets/img/badges/blinkiesCafe-xD.gif",
    "alt": "This page works better on a computer than on a smartphone :3",
    "title": "This page works better on a computer than on a smartphone :3",
    "href": "/assets/img/badges/blinkiesCafe-xD.gif",
    "text_badge": ""
  },
  {
    "src": "/assets/img/badges/blinkiesCafe-tumblr-grrll.gif",
    "alt": "Tumblr",
    "title": "Tumblr Tumblr Tumblr",
    "href": "https://www.tumblr.com/strawmelonjuice",
    "text_badge": ""
  },
  {
    "src": "https://gleam.run/images/lucy/lucy.svg",
    "alt": "",
    "title": "Written in Gleam",
    "href": "https://gleam.run/",
    "text_badge": "Made with Gleam"
  },
  {
    "src": "https://yesterweb.org/no-to-web3/img/roly-saynotoweb3.gif",
    "alt": "Keep the web free, say no to web3",
    "title": "Crypto's ewie",
    "href": "https://yesterweb.org/no-to-web3/",
    "text_badge": ""
  },
  {
    "src": "/assets/img/badges/blinkiesCafe-autism.gif",
    "alt": "autism",
    "title": "brain go brrr",
    "href": "self",
    "text_badge": ""
  },
  {
    "src": "/assets/img/badges/getfirefox.gif",
    "alt": "Get Firefox",
    "title": "GET FIREFOX",
    "href": "https://www.mozilla.org/nl/firefox/new/",
    "text_badge": ""
  },
  {
    "src": "/assets/img/badges/blinkiesCafe-L1.gif",
    "alt": "",
    "title": "I GOT AUTISM",
    "href": "self",
    "text_badge": ""
  },
  {
    "src": "/assets/img/badges/minecraft.gif",
    "alt": "minecraft",
    "title": "block game good",
    "href": "https://polymc.org/",
    "text_badge": ""
  },
  {
    "src": "/assets/img/badges/nerd.gif",
    "alt": "nerd",
    "title": "nerd",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "/assets/img/badges/fucknazis.gif",
    "alt": "Fuck nazis",
    "title": "FUCK NAZIS",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "/assets/img/badges/antinft.gif",
    "alt": "",
    "title": "NFTs are thrash, and a perfect way to spend money on destroying the world.",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "/assets/img/badges/linux80x15.png",
    "alt": "Linux",
    "title": "arch linux btw heheh",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "/assets/img/badges/beingaprincessisafulltimejob.gif",
    "alt": "Being a princess is a full time job",
    "title": "Being a princess is a full time job </3",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "/assets/img/badges/y2k-compliant.gif",
    "alt": "Y2K-Compliant",
    "title": "We survived! We all did!",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "/assets/img/badges/transles80x31.png",
    "alt": "trans-lesbian flag",
    "title": "I'm trans, and... girls... are... awesome!",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "https://blinkies.cafe/b/display/blinkiesCafe-badge.gif",
    "alt": "blinkies.cafe",
    "title": "blinkies.cafe | make your own blinkies!",
    "href": "https://blinkies.cafe",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  },
  {
    "src": "",
    "alt": "",
    "title": "",
    "href": "",
    "text_badge": ""
  }
]"""
